<?php include $phireHeader; ?>
    <h1 class="templates-header"><?=$title; ?> : <span id="title-span"><?=$template_name; ?></span></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'templates', 'add')): ?>
        <nav><a href="<?=$phireUri; ?>/templates/add">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri; ?>/templates">Back</a></nav>
    </nav>
<?=$form; ?>
<?php include $phireFooter; ?>
