<?php include $phireHeader; ?>
<?php if ($acl->isAllowed($user->role, 'templates', 'upload')): ?>
    <form id="asset-upload-form" action="<?=$phireUri . '/templates/upload'; ?>" method="post" enctype="multipart/form-data">
        <div><input tabindex="2" type="submit" id="submit" value="Upload" /></div>
        <div><input tabindex="1" type="file" name="upload_template" id="upload_template" required="required" value="" size="25" /></div>
    </form>
<?php endif; ?>
    <h1 class="templates-header"><?=$title; ?></h1>
<?php if (count($templates) > 0): ?>
<?php if ($acl->isAllowed($user->role, 'templates', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri; ?>/templates/add">+ Add</a></nav>
    </nav>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'templates', 'remove')): ?>
    <form id="templates-form" action="<?=$phireUri . '/templates/remove'; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/templates?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/templates?sort=name';?>">Name</a></th>
                <th><a href="<?=$phireUri . '/templates?sort=visible';?>">Visible</a></th>
                <th>Device</th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'templates', 'copy')): ?>Copy<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'templates', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'templates', 'remove')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_templates" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($templates as $template): ?>
            <tr>
                <td><?=$template->id; ?></td>
                <td><?=$template->name; ?></td>
                <td><?=(($template->visible) ? 'Yes' : 'No'); ?></td>
                <td><?=$template->device; ?></td>
                <td><?php if ($acl->isAllowed($user->role, 'templates', 'copy')): ?><a class="copy-link" href="<?=$phireUri . '/templates/copy/' . $template->id; ?>">Copy</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td><?php if ($acl->isAllowed($user->role, 'templates', 'edit')): ?><a class="edit-link" href="<?=$phireUri . '/templates/edit/' . $template->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'templates', 'remove')): ?><input type="checkbox" name="rm_templates[]" id="rm_templates<?=$i++; ?>" value="<?=$template->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'templates', 'remove')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Remove" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
<?php if ($acl->isAllowed($user->role, 'templates', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri; ?>/templates/add">+ Add</a></nav>
    </nav>
<?php endif; ?>
    <p>There are currently no templates.</p>
<?php endif; ?>
<?php include $phireFooter; ?>